apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bearer-token-service.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bearer-token-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URI: {{ include "bearer-token-service.mongoUri" . | quote }}
  {{- if or .Values.redis.enabled .Values.externalRedis.addr }}
  REDIS_ADDR: {{ include "bearer-token-service.redisAddr" . | quote }}
  {{- end }}
---
{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bearer-token-service.labels" . | nindent 4 }}
    app: mongodb
type: Opaque
stringData:
  username: {{ .Values.mongodb.auth.username | quote }}
  password: {{ .Values.mongodb.auth.password | quote }}
{{- end }}
